#Gradle
org.gradle.jvmargs=-Xmx6144M -Dfile.encoding=UTF-8
kotlin.daemon.jvm.options=-Xmx4096M
org.gradle.caching=true
org.gradle.configuration-cache=true
#Kotlin
kotlin.code.style=official
kotlin.js.compiler=ir
#MPP
kotlin.mpp.enableCInteropCommonization=false
kotlin.native.cacheKind=static
org.gradle.parallel=true
org.gradle.workers.max=4